kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: K0YN+GQdJK6+NcBzRWqYRPvWoNV8cFaMaNqXpcBXDTQ=
      - identity: {}
