kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: beB+RlJHqyD01nq/ElevYnT5JvNbmbSfkwuMkip1+yc=
      - identity: {}
